### ISSUE TITLE
Elements are hidden or partially accessible on some devices size

### ISSUE THREAD

**Issue by njokuScript** [LazerPay-Finance/lazerpay-react-native#7]
[
![Screenshot_20220329-130913_Risevest Dev](https://user-images.githubusercontent.com/38771353/160837881-6690ed9f-a71d-47d1-a784-52899678ca02.jpg)
](url)

**Comment by franko4don** [comment]
is this particularly related to Go back button?

**Comment by njokuScript** [comment]
Nah, its related to the SDK view. The flutter sdk has the same issue
